name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
      deployments: write
    environment:
      name: prd
      url: https://physics.coody.app

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Enable Corepack
        run: corepack enable && corepack prepare yarn@3.6.3 --activate

      - name: Install
        run: yarn install --immutable

      - name: Check
        run: yarn vp check

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=coody-physics-prd-01 --branch=main --commit-dirty=true
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
